local renv = {
    DockWidgetPluginGuiInfo = {
        new,
    },
    warn,
    tostring,
    gcinfo,
    os = {
        clock,
        difftime,
        time,
        date,
    },
    tick,
    task = {
        defer,
        cancel,
        wait,
        desynchronize,
        synchronize,
        delay,
        spawn,
    },
    getfenv,
    debug = {
        dumpheap,
        getmemorycategory,
        resetmemorycategory,
        setmemorycategory,
        dumpcodesize,
        profilebegin,
        loadmodule,
        profileend,
        info,
        tracerefs,
        dumprefs,
        traceback,
    },
    NumberSequence = {
        new,
    },
    assert,
    rawlen,
    wait,
    Color3 = {
        fromHex,
        fromHSV,
        toHSV,
        fromRGB,
        new,
    },
    Enum,
    Delay,
    OverlapParams = {
        new,
    },
    Path2DControlPoint = {
        new,
    },
    SecurityCapabilities = {
        fromCurrent,
        new,
    },
    shared = {
    },
    _G = {
    },
    Faces = {
        new,
    },
    AdReward = {
    },
    error,
    UserSettings,
    Instance = {
        fromExisting,
        new,
    },
    setfenv,
    printidentity,
    coroutine = {
        resume,
        running,
        yield,
        close,
        status,
        wrap,
        create,
        isyieldable,
    },
    string = {
        split,
        match,
        gmatch,
        upper,
        gsub,
        format,
        lower,
        sub,
        pack,
        find,
        char,
        packsize,
        reverse,
        byte,
        unpack,
        rep,
        len,
    },
    NumberRange = {
        new,
    },
    buffer = {
        readf64,
        readu32,
        tostring,
        readi8,
        readu16,
        copy,
        readu8,
        writebits,
        writei16,
        writeu16,
        fromstring,
        writef32,
        readi32,
        fill,
        writeu32,
        writeu8,
        create,
        writestring,
        writei8,
        readbits,
        readi16,
        writef64,
        len,
        writei32,
        readstring,
        readf32,
    },
    PhysicalProperties = {
        new,
    },
    newproxy,
    rawget,
    PluginManager,
    ColorSequence = {
        new,
    },
    Vector2int16 = {
        new,
    },
    Ray = {
        new,
    },
    NumberSequenceKeypoint = {
        new,
    },
    Version,
    Vector2 = {
        min,
        xAxis,
        zero,
        max,
        one,
        yAxis,
        new,
    },
    tonumber,
    Game,
    Content = {
        fromUri,
        fromObject,
        fromAssetId,
        none,
    },
    spawn,
    SharedTable = {
        cloneAndFreeze,
        clear,
        clone,
        isFrozen,
        size,
        increment,
        update,
        new,
    },
    stats,
    xpcall,
    typeof,
    time,
    loadstring,
    print,
    pairs,
    pcall,
    bit32 = {
        band,
        extract,
        byteswap,
        bor,
        bnot,
        countrz,
        bxor,
        arshift,
        rshift,
        rrotate,
        replace,
        lshift,
        lrotate,
        btest,
        countlz,
    },
    Workspace,
    unpack,
    TweenInfo = {
        new,
    },
    ValueCurveKey = {
        new,
    },
    require,
    Vector3 = {
        fromNormalId,
        xAxis,
        zero,
        max,
        min,
        fromAxis,
        zAxis,
        FromAxis,
        one,
        FromNormalId,
        yAxis,
        new,
    },
    table = {
        getn,
        foreachi,
        foreach,
        sort,
        unpack,
        freeze,
        clear,
        pack,
        move,
        insert,
        create,
        maxn,
        isfrozen,
        concat,
        clone,
        find,
        remove,
    },
    Vector3int16 = {
        new,
    },
    setmetatable,
    elapsedTime,
    workspace,
    UDim = {
        new,
    },
    _VERSION,
    ipairs,
    CFrame = {
        identity,
        Angles,
        fromEulerAnglesYXZ,
        fromRotationBetweenVectors,
        lookAlong,
        fromOrientation,
        fromMatrix,
        fromEulerAnglesXYZ,
        fromEulerAngles,
        lookAt,
        fromAxisAngle,
        new,
    },
    rawequal,
    version,
    Region3int16 = {
        new,
    },
    collectgarbage,
    game,
    getmetatable,
    Spawn,
    PluginDrag = {
        new,
    },
    Region3 = {
        new,
    },
    utf8 = {
        offset,
        codepoint,
        nfdnormalize,
        char,
        codes,
        len,
        graphemes,
        nfcnormalize,
        --charpattern = "[\000-�-�][�-�]*",
    },
    CellId = {
        new,
    },
    ypcall,
    rawset,
    PathWaypoint = {
        new,
    },
    DateTime = {
        fromUnixTimestamp,
        now,
        fromIsoDate,
        fromUnixTimestampMillis,
        fromLocalTime,
        fromUniversalTime,
    },
    CatalogSearchParams = {
        new,
    },
    Font = {
        fromId,
        fromEnum,
        fromName,
        new,
    },
    settings,
    User = {
        fromId,
        fromString,
    },
    math = {
        log,
        e,
        ldexp,
        deg,
        cosh,
        round,
        random,
        frexp,
        tanh,
        floor,
        max,
        sqrt,
        modf,
        huge,
        sqrt2,
        pow,
        isnan,
        acos,
        phi,
        tau,
        exp,
        pi,
        isfinite,
        tan,
        cos,
        isinf,
        atan,
        map,
        sign,
        ceil,
        clamp,
        noise,
        abs,
        nan,
        sinh,
        asin,
        min,
        randomseed,
        fmod,
        rad,
        atan2,
        log10,
        sin,
        lerp,
    },
    next,
    Random = {
        new,
    },
    UDim2 = {
        fromOffset,
        fromScale,
        new,
    },
    type,
    RaycastParams = {
        new,
    },
    ElapsedTime,
    select,
    Stats,
    delay,
    Wait,
    FloatCurveKey = {
        new,
    },
    Rect = {
        new,
    },
    BrickColor = {
        Blue,
        White,
        Yellow,
        Red,
        Gray,
        palette,
        New,
        Black,
        Green,
        Random,
        DarkGray,
        random,
        new,
    },
    vector = {
        clamp,
        ceil,
        floor,
        one,
        abs,
        zero,
        create,
        normalize,
        min,
        max,
        magnitude,
        cross,
        sign,
        angle,
        dot,
        lerp,
    },
    Axes = {
        new,
    },
    ColorSequenceKeypoint = {
        new,
    },
    RotationCurveKey = {
        new,
    },
}

return function()
    return renv
end
